version: "3"

services:
  web:
    image: wordpress
    links:
      - mysql
    environment:
      - WORDPRESS_DB_PASSWORD=wordpress
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./dev/wp:/var/www/html
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress
      - MYSQL_DATABASE=wordpress
